# Generated by Django 3.1.7 on 2021-04-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=20)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderJson', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=35)),
                ('zip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default='', max_length=60)),
                ('prod_id', models.CharField(default='', max_length=10)),
                ('prod_desc', models.CharField(default='', max_length=1000)),
                ('prod_date', models.DateField()),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=40)),
                ('price', models.IntegerField(default=0)),
                ('images', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateTracker',
            fields=[
                ('order_id', models.CharField(max_length=50)),
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_desc', models.CharField(max_length=35)),
                ('timeNow', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
