# Generated by Django 3.1.7 on 2021-04-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
