# Generated by Django 3.1.7 on 2021-04-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210411_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_id',
            field=models.CharField(default='', max_length=60),
        ),
    ]
