# Generated by Django 3.1.7 on 2021-04-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('heading0', models.CharField(default='', max_length=500)),
                ('content_heading0', models.CharField(default='', max_length=5000)),
                ('heading1', models.CharField(default='', max_length=500)),
                ('content_heading1', models.CharField(default='', max_length=5000)),
                ('heading2', models.CharField(default='', max_length=500)),
                ('content_heading2', models.CharField(default='', max_length=5000)),
                ('post_date', models.DateField()),
            ],
        ),
    ]
